### ISSUE TITLE
[Enhancement]: 

### ISSUE THREAD

**Issue by Runner822** [LemonLoader/MelonLoader_057#17]
### Describe the new feature or enhancement

Bonelab Fusion Dev say lemonloader has bugs
i dont know what bug cuz im not dev

**Comment by Maximusprime23** [comment]
Go read the bugs on the lemonloader github page all of the bugs are listed here some bugs seem to be fixed like the patch bug but we are not sure if other bugs can be fixed and we're not sure if fusion can work since it uses steam networking and other complicated things so fusion quest is in the works with no guarantee but we are getting slight progress but still no guarantee

**Comment by TrevTV** [comment]
I already know this.
